### ISSUE TITLE
Namespace all classes

### ISSUE THREAD

**Issue by oskargargas** [wuminzhe/scale_rb#3]
Hi! First of all thanks for your work. It's much appreciated. If it's ok, I'll raise few issues as I try to incorporate your library into my codebase.

First thing I noticed are classes outside `ScaleRb` namespace. In my project I have `Address` class which represents regular street addresses. After adding this gem it was extended with cryptoaddress methods. This might lead to name collision and other problems.

**Comment by wuminzhe** [comment]
sorry for late, I will fix this

**Comment by wuminzhe** [comment]
@oskargargas I have moved all things to the `ScaleRb` namespace. you can try 0.2.0

you can email me(wuminzhe@gmail.com) or find me on discord with `_akiwu`
